In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [2]:
omicron_data = pd.read_csv('C:\\Users\\Athiban\\Desktop\\Kee\\omicron.csv' , na_values=' ?')
omicron_data.head(5)

id             user_name   user_location  \
0  1465693385088323591                Abaris           Hants   
1  1465693062999412746                GFTs         Lalaland   
2  1465690116442279942  Herbie Finkle (Cozy)             NaN   
3  1465689607165591552     Electrical Review  United Kingdom   
4  1465688203709464578       BingX Academy 🔑             NaN   

                                    user_description         user_created  \
0  Would appear on Blogger (did originally),  but...  2009-09-16 14:30:32   
1  There's a field somewhere beyond all doubt and...  2019-12-28 14:29:13   
2                           help me find me frens ❤️  2021-07-10 09:40:57   
3  Electrical Review is a monthly journal aimed a...  2009-05-21 08:32:19   
4  BingX (Prev. Bingbon) is the world's top crypt...  2013-12-31 02:57:32   

   user_followers  user_friends  user_favourites  user_verified  \
0            2880          4369            26907          False   
1             165           583            21152          False   
2             114           393             2339          False   
3           20759          2321              739          False   
4           17134             8               31          False   

                  date                                               text  \
0  2021-11-30 14:45:08  @SkyNews "Told you I'd be Back!" #OMICRON “Odi...   
1  2021-11-30 14:43:52  Someone told me this in October #Omicron https...   
2  2021-11-30 14:32:09  Glad to see the public schoolkids are wrapping...   
3  2021-11-30 14:30:08  #Automation systems have become increasingly c...   
4  2021-11-30 14:24:33  🟢 If u think Omicron is a FUD, you LONG📈\n🔴 If...   

         hashtags               source  retweets  favorites  is_retweet  
0     ['OMICRON']      Twitter Web App         0          0       False  
1     ['Omicron']  Twitter for Android         0          0       False  
2       ['COVID']      Twitter Web App         0          1       False  
3  ['Automation']       Hootsuite Inc.         0          0       False  
4             NaN      Twitter Web App         2          2       False

In [3]:
omicron_data.isna().sum()

id                     0
user_name              0
user_location       6452
user_description    1754
user_created           0
user_followers         0
user_friends           0
user_favourites        0
user_verified          0
date                   0
text                   0
hashtags            6787
source                 0
retweets               0
favorites              0
is_retweet             0
dtype: int64

In [6]:
# now , these 3 coulmns are catorigal column, hence i am going to impute some missing values for numerical column, here i am going to take id column

np.random.seed(seed=0)
i = np.random.choice(a=omicron_data.index,replace = False, size = 20)
omicron_data.loc[i,'id'] = np.nan
omicron_data.isna().sum()

id                    20
user_name              0
user_location       6452
user_description    1754
user_created           0
user_followers         0
user_friends           0
user_favourites        0
user_verified          0
date                   0
text                   0
hashtags            6787
source                 0
retweets               0
favorites              0
is_retweet             0
dtype: int64

In [8]:
x_train,x_test,y_train,y_test = train_test_split(omicron_data.drop('is_retweet', axis =1),
                                                 omicron_data['is_retweet'],
                                                 test_size=0.2,
                                                 random_state=30)

In [9]:
si_id = SimpleImputer(strategy='mean', add_indicator=True)

In [11]:
si_id.fit_transform(x_train[['id']])

array([[1.46703026e+18, 0.00000000e+00],
       [1.46741780e+18, 0.00000000e+00],
       [1.46694155e+18, 0.00000000e+00],
       ...,
       [1.46747082e+18, 0.00000000e+00],
       [1.46596534e+18, 0.00000000e+00],
       [1.46592857e+18, 0.00000000e+00]])

In [18]:
a = pd.DataFrame(si_id.fit_transform(x_train[['id']]))

In [13]:
si_id.statistics_

array([1.46721533e+18])

In [20]:
a[1]==1

0        False
1        False
2        False
3        False
4        False
         ...  
21729    False
21730    False
21731    False
21732    False
21733    False
Name: 1, Length: 21734, dtype: bool

In [21]:
a[a[1]==1]

0    1
477    1.467215e+18  1.0
3431   1.467215e+18  1.0
4674   1.467215e+18  1.0
4840   1.467215e+18  1.0
7240   1.467215e+18  1.0
9873   1.467215e+18  1.0
11645  1.467215e+18  1.0
14111  1.467215e+18  1.0
14193  1.467215e+18  1.0
14312  1.467215e+18  1.0
14761  1.467215e+18  1.0
18952  1.467215e+18  1.0
20128  1.467215e+18  1.0
20148  1.467215e+18  1.0

In [ ]:
# if you have missing values in a catogorical column 
#numerical clm --> strategy --> mean/mode/std/median (no outlier - mean , outlier - median)
#string / catogrocal clm --> strategy --> constant / most_frequent

In [22]:
omicron_data.isna().sum()

id                    20
user_name              0
user_location       6452
user_description    1754
user_created           0
user_followers         0
user_friends           0
user_favourites        0
user_verified          0
date                   0
text                   0
hashtags            6787
source                 0
retweets               0
favorites              0
is_retweet             0
dtype: int64

In [25]:
si_location = SimpleImputer(strategy='constant',add_indicator=True,fill_value = 'Not avialble')

In [27]:
si_location.fit_transform(x_train[['user_location']])

array([['Not avialble', True],
       ['Antarctica', False],
       ['Louisville, KY', False],
       ...,
       ['Ardlethan', False],
       ['Not avialble', True],
       ['Not avialble', True]], dtype=object)

In [29]:
b = pd.DataFrame(si_location.fit_transform(x_train[['user_location']]))
b

0      1
0            Not avialble   True
1              Antarctica  False
2          Louisville, KY  False
3                   India  False
4             Ala Biafra🔯  False
...                   ...    ...
21729  Louth Lincolnshire  False
21730     Los Angeles, CA  False
21731           Ardlethan  False
21732        Not avialble   True
21733        Not avialble   True

[21734 rows x 2 columns]

In [32]:
#want to do for x_test also, you need to use transform

si_id.transform(x_test[['id']])


array([[1.46940399e+18, 0.00000000e+00],
       [1.46597419e+18, 0.00000000e+00],
       [1.46564975e+18, 0.00000000e+00],
       ...,
       [1.46746605e+18, 0.00000000e+00],
       [1.46595041e+18, 0.00000000e+00],
       [1.46833725e+18, 0.00000000e+00]])

In [34]:
b= pd.DataFrame(si_id.transform(x_test[['id']]))
b

0    1
0     1.469404e+18  0.0
1     1.465974e+18  0.0
2     1.465650e+18  0.0
3     1.467329e+18  0.0
4     1.468444e+18  0.0
...            ...  ...
5429  1.465687e+18  0.0
5430  1.469523e+18  0.0
5431  1.467466e+18  0.0
5432  1.465950e+18  0.0
5433  1.468337e+18  0.0

[5434 rows x 2 columns]

In [35]:
b[1]==1

0       False
1       False
2       False
3       False
4       False
        ...  
5429    False
5430    False
5431    False
5432    False
5433    False
Name: 1, Length: 5434, dtype: bool

In [36]:
b[b[1]==1]

0    1
1261  1.467215e+18  1.0
2197  1.467215e+18  1.0
2867  1.467215e+18  1.0
3410  1.467215e+18  1.0
3525  1.467215e+18  1.0
5313  1.467215e+18  1.0